parameters:
#    wk_dhl_api.example.class: Wk\DhlApiBundle\Example

services:
#    wk_dhl_api.example:
#        class: %wk_dhl_api.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
